### ISSUE TITLE
Crash without PHPUnit installed

### ISSUE THREAD

**Issue by jtojnar** [TomasVotruba/barista#2]
Running `vendor/bin/barista analyze app` in a Nette project that does not use PHPUnit (`nette/tester` is okay) crashes:

```
Fatal error: Uncaught Error: Class "PHPUnit\Framework\TestCase" not found in /home/jtojnar/Projects/eudyptes/vendor/barista/barista/src/Testing/Macro/AbstractMacroTest.php:22
Stack trace:
#0 /home/jtojnar/Projects/eudyptes/vendor/composer/ClassLoader.php(571): include()
#1 /home/jtojnar/Projects/eudyptes/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/jtojnar/P...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Barista\\Testing...')
#3 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Extensions/SearchExtension.php(97): class_exists('Barista\\Testing...')
#4 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Extensions/SearchExtension.php(72): Nette\DI\Extensions\SearchExtension->findClasses(Object(stdClass))
#5 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Compiler.php(241): Nette\DI\Extensions\SearchExtension->loadConfiguration()
#6 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Compiler.php(211): Nette\DI\Compiler->processExtensions()
#7 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerLoader.php(119): Nette\DI\Compiler->compile()
#8 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerLoader.php(81): Nette\DI\ContainerLoader->generate('Container_55cc0...', Array)
#9 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerLoader.php(44): Nette\DI\ContainerLoader->loadFile('Container_55cc0...', Array)
#10 /home/jtojnar/Projects/eudyptes/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(274): Nette\DI\ContainerLoader->load(Array, Array)
#11 /home/jtojnar/Projects/eudyptes/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(252): Nette\Bootstrap\Configurator->loadContainer()
#12 /home/jtojnar/Projects/eudyptes/vendor/barista/barista/src/DI/BaristaContainerFactory.php(32): Nette\Bootstrap\Configurator->createContainer()
#13 /home/jtojnar/Projects/eudyptes/vendor/barista/barista/bin/barista.php(31): Barista\DI\BaristaContainerFactory->create(Array)
#14 /home/jtojnar/Projects/eudyptes/vendor/barista/barista/bin/barista(4): require('/home/jtojnar/P...')
#15 /home/jtojnar/Projects/eudyptes/vendor/bin/barista(117): include('/home/jtojnar/P...')
#16 {main}
  thrown in /home/jtojnar/Projects/eudyptes/vendor/barista/barista/src/Testing/Macro/AbstractMacroTest.php on line 22
```

**Comment by jtojnar** [comment]
Even if I install phpunit, it still crashes with a different error:

```
Fatal error: Uncaught Nette\DI\ServiceCreationException: Service 'application.1' (type of App\Presenters\DashboardPresenter): Service of type App\Model\HelperLoader required by $helperLoader in App\Presenters\BasePresenter::__construct() not found. Did you add it to configuration file? in /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Resolver.php:650
Stack trace:
#0 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Resolver.php(577): Nette\DI\Resolver::autowireArgument(Object(ReflectionParameter), Object(Closure))
#1 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Resolver.php(232): Nette\DI\Resolver::autowireArguments(Object(ReflectionMethod), Array, Object(Closure))
#2 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Definitions/ServiceDefinition.php(226): Nette\DI\Resolver->completeStatement(Object(Nette\DI\Definitions\Statement))
#3 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Resolver.php(168): Nette\DI\Definitions\ServiceDefinition->complete(Object(Nette\DI\Resolver))
#4 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerBuilder.php(332): Nette\DI\Resolver->completeDefinition(Object(Nette\DI\Definitions\ServiceDefinition))
#5 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Compiler.php(275): Nette\DI\ContainerBuilder->complete()
#6 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Compiler.php(212): Nette\DI\Compiler->processBeforeCompile()
#7 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerLoader.php(119): Nette\DI\Compiler->compile()
#8 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerLoader.php(81): Nette\DI\ContainerLoader->generate('Container_55cc0...', Array)
#9 /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/ContainerLoader.php(44): Nette\DI\ContainerLoader->loadFile('Container_55cc0...', Array)
#10 /home/jtojnar/Projects/eudyptes/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(274): Nette\DI\ContainerLoader->load(Array, Array)
#11 /home/jtojnar/Projects/eudyptes/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(252): Nette\Bootstrap\Configurator->loadContainer()
#12 /home/jtojnar/Projects/eudyptes/vendor/barista/barista/src/DI/BaristaContainerFactory.php(32): Nette\Bootstrap\Configurator->createContainer()
#13 /home/jtojnar/Projects/eudyptes/vendor/barista/barista/bin/barista.php(31): Barista\DI\BaristaContainerFactory->create(Array)
#14 /home/jtojnar/Projects/eudyptes/vendor/barista/barista/bin/barista(4): require('/home/jtojnar/P...')
#15 /home/jtojnar/Projects/eudyptes/vendor/bin/barista(117): include('/home/jtojnar/P...')
#16 {main}
  thrown in /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Resolver.php on line 650
```

Perhaps it is not supposed to be installed with `composer require barista/barista --dev`?

**Comment by jtojnar** [comment]
Running `composer install` in `vendor/barista/barista/` seems to fix it but is that really expected?

**Comment by TomasVotruba** [comment]
The 1st error - for some reason it tries to register this testcase as a service:
https://github.com/TomasVotruba/barista/blob/main/src/Testing/Macro/AbstractMacroTest.php

Would excluding the class in here help?
https://github.com/TomasVotruba/barista/blob/b1ee06bfeaa621605ba0adfc901b94fcdfe68654/config/services.neon#L5

**Comment by jtojnar** [comment]
Excluding does not seem to work.

The search extension checks for the class existence

https://github.com/nette/di/blob/1b2d3716c51f36f1b71780d5b0594cd0a258fa99/src/DI/Extensions/SearchExtension.php#L93

before checking if it is excluded

https://github.com/nette/di/blob/1b2d3716c51f36f1b71780d5b0594cd0a258fa99/src/DI/Extensions/SearchExtension.php#L108

I verified by dumping `$config` [here](https://github.com/nette/di/blob/1b2d3716c51f36f1b71780d5b0594cd0a258fa99/src/DI/Extensions/SearchExtension.php#L76) and it only ever prints:

```php
object(stdClass)#205 (7) {
  ["in"]=>
  string(71) "/home/jtojnar/Projects/eudyptes/vendor/barista/barista/src/DI/../../src"
  ["exclude"]=>
  object(stdClass)#201 (3) {
    ["classes"]=>
    array(3) {
      [0]=>
      string(39) "Barista\Testing\Macro\AbstractMacroTest"
      [1]=>
      string(34) "Barista\DI\BaristaContainerFactory"
      [2]=>
      string(28) "Barista\Configuration\Option"
    }
    ["implements"]=>
    array(1) {
      [0]=>
      string(39) "Barista\Contract\LatteUpgraderInterface"
    }
    ["extends"]=>
    array(0) {
    }
  }
  ["files"]=>
  array(0) {
  }
  ["classes"]=>
  array(0) {
  }
  ["extends"]=>
  array(0) {
  }
  ["implements"]=>
  array(0) {
  }
  ["tags"]=>
  array(0) {
  }
}
```

**Comment by TomasVotruba** [comment]
I see. And the class existance probably invokes the parent class autoloading.
What do you suggest to overcome this?

**Comment by jtojnar** [comment]
You are probably more qualified to answer that.

Is it not possible to use Composer autoloading for Nette autowiring? It seems to work pretty well in app projects (unless Nette somehow still uses RobotLoader internally) but I am not really sure how it is supposed to work in tools installed as Composer dependencies. I would expect them to just use the autoloader of the parent project but removing the `search` section of the config just results in broken autowiring:

```php
Fatal error: Uncaught Nette\DI\MissingServiceException: Service of type Barista\FileSystem\LatteFilesFinder not found. Did you add it to configuration file? in /home/jtojnar/Projects/eudyptes/vendor/nette/di/src/DI/Autowiring.php:57
```

**Comment by TomasVotruba** [comment]
I don't know how exactly the search componet works. 

I think that to make code work, we have to:

* move the test case class
* or add phpunit as required dependency

It should be still available without installing phpunit as extra dependency.

**Comment by jtojnar** [comment]
It [loads the app’s autoload file](https://github.com/TomasVotruba/barista/blob/b1ee06bfeaa621605ba0adfc901b94fcdfe68654/bin/barista.php#L9) and `vendor/composer/autoload_psr4.php` contains `'Barista\\' => array($vendorDir . '/barista/barista/src'),`.

Actually looking at the [autowiring code](https://github.com/nette/di/blob/9878f2958a0a804b08430dbc719a52e493022739/src/DI/Autowiring.php#L57), it is able to find the class, or it would crash with a [different error](https://github.com/nette/di/blob/9878f2958a0a804b08430dbc719a52e493022739/src/DI/Autowiring.php#L54). Will do more dumping.

**Comment by TomasVotruba** [comment]
My rought guess is that it crashes on `class_parents()` here:
https://github.com/nette/di/blob/9878f2958a0a804b08430dbc719a52e493022739/src/DI/Autowiring.php#L106

**Comment by jtojnar** [comment]
That behaviour is probably intentional so that Nette DI does not create random classes.

Another alternative could be removing the RobotLoader in favour of explicitly listed factories. The following seems to work for the `analyze` command:

```patch
--- a/config/services.neon
+++ b/config/services.neon
@@ -1,14 +1,3 @@
-# autodiscovery, see https://doc.nette.org/en/dependency-injection/configuration#toc-search
-search:
-    in: %appDir%/../../src
-    exclude:
-        classes:
-            - Barista\DI\BaristaContainerFactory
-            - Barista\Configuration\Option
-        implements:
-            # register manually the rules you want to apply
-            - Barista\Contract\LatteUpgraderInterface
-
 decorator:
     Barista\Command\AbstractBaristaCommand:
         inject: true
@@ -21,6 +10,9 @@
         class: Barista\Command\LintCommand
         arguments:
             latteProviderFile: %latteProviderFile%
+
+    - Barista\FileSystem\LatteFilesFinder
+    - Barista\Console\ApplicationFactory
 
     - Latte\Compiler\TemplateParser
     - Latte\Compiler\TemplateLexer
```

Well, “work” it will then print the same error as in the [second comment](https://github.com/TomasVotruba/barista/issues/2#issuecomment-1142079839). But that is probably unrelated issue.

**Comment by TomasVotruba** [comment]
That would force us to register everything manually and kill the point of Nette 3.0 search feature.

**Comment by jtojnar** [comment]
> My rought guess is that it crashes on `class_parents()` here:
> [nette/di@`9878f29`/src/DI/Autowiring.php#L106](https://github.com/nette/di/blob/9878f2958a0a804b08430dbc719a52e493022739/src/DI/Autowiring.php#L106)

No, it crashed in Composer autoloader code triggered by the [`class_exist` call in the search extension](https://github.com/nette/di/blob/1b2d3716c51f36f1b71780d5b0594cd0a258fa99/src/DI/Extensions/SearchExtension.php#L92) on the `AbstractMacroTest`. That was pretty clear from the initial trace.



> That would force us to register everything manually and kill the point of Nette 3.0 search feature.

Not everything, just the stuff we want auto-wired. Which, at the moment seems to be the two classes listed in [my patch](https://github.com/TomasVotruba/barista/issues/2#issuecomment-1142131371).

To be honest, I have always felt that RobotLoader is a misfeature since Composer already has all the necessary information available statically (as long as you use Composer autoloading – but there is no excuse to avoid it these days, IMO). Unless I am missing something, the search extension should be able to look at all the explicitly registered services and try to register their dependencies, rather than scanning a directory and registering all classes it finds it does now.

**Comment by TomasVotruba** [comment]
I want to keep the search here, to allow scaling services without thinking about manual registration. I'm doing the same in Symfony last 4 years.

**Comment by TomasVotruba** [comment]
This should fix it: https://github.com/TomasVotruba/barista/commit/08fa2dfd2e4d2027f2f6029be780e647b43f867c

Barista is a dev tool with abstract test case, so the PHPUnit is expected here. 
Could you create a new issue for the application case? Ideally with small reproducer repository, as it seems very random.

**Comment by jtojnar** [comment]
Thanks, will do. I have opened https://github.com/nette/di/issues/282 just in case it ditching the RobotLoader is interesting for David.

**Comment by jtojnar** [comment]
Though pondering it a bit more, the abstract test case is not really relevant to the dev tool so it might be cleanest to split it into a separate composer package. Though I understand that adding an extra dependency is probably the most pragmatic choice.

**Comment by TomasVotruba** [comment]
At first sight, it would hell to maintain for a just a few classes. 

Yet the test case is very useful for the upgrade. It should be part of the Latte 2 project already, while this package runs on Latte 3.
I might re-thing to drop it and separate in the future. This package is really young so we'll see where it grows :). I didn't expect any activity first months TBH.
